name: CI                    # display name in the GitHub UI

on: [push]                  # WHEN to run: every git push

jobs:
  # ------------------------------------------------------------------------------------------------------
  # C++ demo build - How a C++ developer uses the repo
  # ------------------------------------------------------------------------------------------------------
  build:                   # a job id (your choice of name)
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, macos-latest, windows-latest] # VM to rent 
  
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
      
      - name: Code compilation
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j --config Release
  
  # ------------------------------------------------------------------------------------------------------
  # Python bindings - How a python develop uses the repo
  # ------------------------------------------------------------------------------------------------------
  python-bindings:
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-22.04, ubuntu-latest, macos-latest, windows-latest]
          python-version: ["3.9", "3.12"]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
            python-version: ${{matrix.python-version}}
      
      - name: Install
        run: pip install .

      - name: Smoke test
        run: python -c "import zombie; print(zombie.__file__)"

  # ------------------------------------------------------------------------------------------------------
  # Legacy build
  # ------------------------------------------------------------------------------------------------------
  legacy_build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Install toolchain
        run: apt-get update && apt-get install -y build-essential cmake git
      
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
      
      - name: Code compilation
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j --config Release
